image: python:3.8

cache:
  key: "project-${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - publish

publish:
  stage: publish
  script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry build
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine --verbose upload --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
